### ISSUE TITLE
Question: is it possible to create out-of-tree drivers in free-standing examples created by VScode-nRF Connect extension? 

### ISSUE THREAD

**Issue by LeoSunTL** [teslabs/zds-2022-drivers-app#1]
Found an example [out_of_tree_driver](https://github.com/nrfconnect/sdk-zephyr/tree/main/samples/application_development/out_of_tree_driver) and it can be created as a free-standing application by vs-ncs extension.
I was about to start my journey with that simple example then I saw your wonderful presentation.
So the question is, is it possible to create custom boards/drivers/bindings with that simple free-standing "out_of_tree_driver" example?

**Comment by gmarull** [comment]
I'd suggest following the approach taken here for what you ask.
