### ISSUE TITLE
The code can't be compiled on Win10

### ISSUE THREAD

**Issue by bvm84** [teslabs/zds-2022-drivers-app#2]
I't trying to find an teamplate for OOT driver to implement custom ST77335S driver for nrf52832. The sample code do not compile. 

bvm84@DESKTOP-PUP6IKC MINGW64 /c/code/zds-2022-drivers-app/app (main)
$ west build -b nrf52840dk_nrf52840 -s app
-- west build: generating a build system
Loading Zephyr default modules (Zephyr base).
-- Application: C:/code/zds-2022-drivers-app/app/app
-- CMake version: 3.20.5
-- Found Python3: C:/code/toolchains/31f4403e35/opt/bin/python.exe (found suitable exact version "3.8.2") found components: Interpreter
-- Cache files will be written to: C:/code/zds-2022-drivers-app/zephyr/.cache
-- Zephyr version: 3.4.99 (C:/code/zds-2022-drivers-app/zephyr)
-- Found west (found suitable version "1.0.0", minimum required is "0.14.0")
-- Board: nrf52840dk_nrf52840
-- Found host-tools: zephyr 0.16.0 (C:/code/toolchains/31f4403e35/opt/zephyr-sdk)
-- Found toolchain: zephyr 0.16.0 (C:/code/toolchains/31f4403e35/opt/zephyr-sdk)
-- Found Dtc: C:/code/toolchains/31f4403e35/opt/bin/dtc.exe (found suitable version "1.4.7", minimum required is "1.4.6")
-- Found BOARD.dts: C:/code/zds-2022-drivers-app/zephyr/boards/arm/nrf52840dk_nrf52840/nrf52840dk_nrf52840.dts
-- Found devicetree overlay: C:/code/zds-2022-drivers-app/app/app/boards/nrf52840dk_nrf52840.overlay
-- Generated zephyr.dts: C:/code/zds-2022-drivers-app/app/build/zephyr/zephyr.dts
-- Generated devicetree_generated.h: C:/code/zds-2022-drivers-app/app/build/zephyr/include/generated/devicetree_generated.h
-- Including generated dts.cmake file: C:/code/zds-2022-drivers-app/app/build/zephyr/dts.cmake
Parsing C:/code/zds-2022-drivers-app/zephyr/Kconfig
Loaded configuration 'C:/code/zds-2022-drivers-app/zephyr/boards/arm/nrf52840dk_nrf52840/nrf52840dk_nrf52840_defconfig'
Merged configuration 'C:/code/zds-2022-drivers-app/app/app/prj.conf'
Configuration saved to 'C:/code/zds-2022-drivers-app/app/build/zephyr/.config'
Kconfig header saved to 'C:/code/zds-2022-drivers-app/app/build/zephyr/include/generated/autoconf.h'
-- Found GnuLd: c:/code/toolchains/31f4403e35/opt/zephyr-sdk/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd.exe (found version "2.38")
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- The ASM compiler identification is GNU
-- Found assembler: C:/code/toolchains/31f4403e35/opt/zephyr-sdk/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc.exe
-- Configuring done
-- Generating done
-- Build files have been written to: C:/code/zds-2022-drivers-app/app/build
←[92m-- west build: building application
[1/245] Generating include/generated/version.h
-- Zephyr version: 3.4.99 (C:/code/zds-2022-drivers-app/zephyr), build: zephyr-v3.4.0-1069-g77aafa51a1b5
[203/245] Building C object modules/app/drivers/sensor/jm101/CMakeFiles/..__app__drivers__sensor__jm101.dir/jm101.c.obj
FAILED: modules/app/drivers/sensor/jm101/CMakeFiles/..__app__drivers__sensor__jm101.dir/jm101.c.obj
C:\code\toolchains\31f4403e35\opt\zephyr-sdk\arm-zephyr-eabi\bin\arm-zephyr-eabi-gcc.exe -DKERNEL -DNRF52840_XXAA -D__PROGRAM_START -D__ZEPHYR__=1 -IC:/code/zds-2022-drivers-app/zephyr/include -Izephyr/include/generated -IC:/code/zds-2022-drivers-app/zephyr/soc/arm/nordic_nrf/nrf52 -IC:/code/zds-2022-drivers-app/zephyr/soc/arm/nordic_nrf/common/. -IC:/code/zds-2022-drivers-app/zephyr/subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/nrfx_glue -IC:/code/zds-2022-drivers-app/zephyr/subsys/bluetooth -I../include -IC:/code/zds-2022-drivers-app/modules/hal/cmsis/CMSIS/Core/Include -IC:/code/zds-2022-drivers-app/modules/hal/nordic/nrfx -IC:/code/zds-2022-drivers-app/modules/hal/nordic/nrfx/drivers/include -IC:/code/zds-2022-drivers-app/modules/hal/nordic/nrfx/mdk -IC:/code/zds-2022-drivers-app/zephyr/modules/hal_nordic/nrfx/. -IC:/code/zds-2022-drivers-app/modules/debug/segger/SEGGER -IC:/code/zds-2022-drivers-app/modules/debug/segger/Config -IC:/code/zds-2022-drivers-app/zephyr/modules/segger/. -IC:/code/zds-2022-drivers-app/modules/crypto/tinycrypt/lib/include -isystem C:/code/zds-2022-drivers-app/zephyr/lib/libc/minimal/include -isystem c:/code/toolchains/31f4403e35/opt/zephyr-sdk/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/include -isystem c:/code/toolchains/31f4403e35/opt/zephyr-sdk/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/include-fixed -fno-strict-aliasing -Os -imacros C:/code/zds-2022-drivers-app/app/build/zephyr/include/generated/autoconf.h -ffreestanding -fno-common -g -gdwarf-4 -fdiagnostics-color=always -mcpu=cortex-m4 -mthumb -mabi=aapcs -mfp16-format=ieee --sysroot=C:/code/toolchains/31f4403e35/opt/zephyr-sdk/arm-zephyr-eabi/arm-zephyr-eabi -imacros C:/code/zds-2022-drivers-app/zephyr/include/zephyr/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-pointer-sign -Wpointer-arith -Wexpansion-to-defined -Wno-unused-but-set-variable -Werror=implicit-int -fno-pic -fno-pie -fno-asynchronous-unwind-tables -fno-reorder-functions --param=min-pagesize=0 -fno-defer-pop -fmacro-prefix-map=C:/code/zds-2022-drivers-app/app/app=CMAKE_SOURCE_DIR -fmacro-prefix-map=C:/code/zds-2022-drivers-app/zephyr=ZEPHYR_BASE -fmacro-prefix-map=C:/code/zds-2022-drivers-app=WEST_TOPDIR -ffunction-sections -fdata-sections -std=c99 -nostdinc -MD -MT modules/app/drivers/sensor/jm101/CMakeFiles/..__app__drivers__sensor__jm101.dir/jm101.c.obj -MF modules\app\drivers\sensor\jm101\CMakeFiles\..__app__drivers__sensor__jm101.dir\jm101.c.obj.d -o modules/app/drivers/sensor/jm101/CMakeFiles/..__app__drivers__sensor__jm101.dir/jm101.c.obj -c C:/code/zds-2022-drivers-app/app/drivers/sensor/jm101/jm101.c
In file included from C:/code/zds-2022-drivers-app/zephyr/include/zephyr/sys/util_macro.h:34,
                 from C:/code/zds-2022-drivers-app/zephyr/include/zephyr/sys/util.h:17,
                 from C:/code/zds-2022-drivers-app/zephyr/include/zephyr/devicetree.h:25,
                 from C:/code/zds-2022-drivers-app/zephyr/include/zephyr/device.h:12,
                 from C:/code/zds-2022-drivers-app/app/drivers/sensor/jm101/jm101.c:8:
C:/code/zds-2022-drivers-app/zephyr/include/zephyr/device.h:85:41: error: '__device_dts_ord_134' undeclared here (not in a function); did you mean '__device_dts_ord_13'?
   85 | #define DEVICE_NAME_GET(dev_id) _CONCAT(__device_, dev_id)
      |                                         ^~~~~~~~~
C:/code/zds-2022-drivers-app/zephyr/include/zephyr/sys/util_internal.h:72:26: note: in definition of macro '__DEBRACKET'
   72 | #define __DEBRACKET(...) __VA_ARGS__
      |                          ^~~~~~~~~~~
C:/code/zds-2022-drivers-app/zephyr/include/zephyr/sys/util_internal.h:64:9: note: in expansion of macro '__GET_ARG2_DEBRACKET'
   64 |         __GET_ARG2_DEBRACKET(one_or_two_args _if_code, _else_code)
      |         ^~~~~~~~~~~~~~~~~~~~
C:/code/zds-2022-drivers-app/zephyr/include/zephyr/sys/util_internal.h:59:9: note: in expansion of macro '__COND_CODE'
   59 |         __COND_CODE(_XXXX##_flag, _if_1_code, _else_code)
      |         ^~~~~~~~~~~
C:/code/zds-2022-drivers-app/zephyr/include/zephyr/sys/util_macro.h:180:9: note: in expansion of macro 'Z_COND_CODE_1'
  180 |         Z_COND_CODE_1(_flag, _if_1_code, _else_code)
      |         ^~~~~~~~~~~~~
C:/code/zds-2022-drivers-app/zephyr/include/zephyr/devicetree.h:4039:9: note: in expansion of macro 'COND_CODE_1'
 4039 |         COND_CODE_1(DT_HAS_COMPAT_STATUS_OKAY(DT_DRV_COMPAT),   \
      |         ^~~~~~~~~~~
C:/code/zds-2022-drivers-app/zephyr/include/zephyr/toolchain/common.h:133:23: note: in expansion of macro '_DO_CONCAT'
  133 | #define _CONCAT(x, y) _DO_CONCAT(x, y)
      |                       ^~~~~~~~~~
C:/code/zds-2022-drivers-app/zephyr/include/zephyr/device.h:85:33: note: in expansion of macro '_CONCAT'
   85 | #define DEVICE_NAME_GET(dev_id) _CONCAT(__device_, dev_id)
      |                                 ^~~~~~~
C:/code/zds-2022-drivers-app/zephyr/include/zephyr/device.h:211:37: note: in expansion of macro 'DEVICE_NAME_GET'
  211 | #define DEVICE_DT_NAME_GET(node_id) DEVICE_NAME_GET(Z_DEVICE_DT_DEV_ID(node_id))
      |                                     ^~~~~~~~~~~~~~~
C:/code/zds-2022-drivers-app/zephyr/include/zephyr/device.h:228:34: note: in expansion of macro 'DEVICE_DT_NAME_GET'
  228 | #define DEVICE_DT_GET(node_id) (&DEVICE_DT_NAME_GET(node_id))
      |                                  ^~~~~~~~~~~~~~~~~~
C:/code/zds-2022-drivers-app/app/drivers/sensor/jm101/jm101.c:626:25: note: in expansion of macro 'DEVICE_DT_GET'
  626 |                 .uart = DEVICE_DT_GET(DT_INST_BUS(i)),                         \
      |                         ^~~~~~~~~~~~~
zephyr/include/generated/devicetree_generated.h:14807:48: note: in expansion of macro 'JM101_DEFINE'
14807 | #define DT_FOREACH_OKAY_INST_zeantec_jm101(fn) fn(0)
      |                                                ^~
C:/code/zds-2022-drivers-app/zephyr/include/zephyr/sys/util_internal.h:105:36: note: in expansion of macro 'DT_FOREACH_OKAY_INST_zeantec_jm101'
  105 | #define UTIL_PRIMITIVE_CAT(a, ...) a##__VA_ARGS__
      |                                    ^
C:/code/zds-2022-drivers-app/app/drivers/sensor/jm101/jm101.c:637:1: note: in expansion of macro 'DT_INST_FOREACH_STATUS_OKAY'
  637 | DT_INST_FOREACH_STATUS_OKAY(JM101_DEFINE)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
[208/245] Building C object modules/hal_nordic/nrfx/CMakeF...ers-app/modules/hal/nordic/nrfx/drivers/src/nrfx_ppi.c.obj
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: 'C:\code\toolchains\31f4403e35\opt\bin\cmake.EXE' --build 'C:\code\zds-2022-drivers-app\app\build'

**Comment by gpauldev** [comment]
Not compiling on a mac M1 and on a fresh Windows 10 installation.
Could be great to have this working as it could be of a great support to understand out of tree device development.

**Comment by paultino** [comment]
Same issue, not compiling.
node '/soc/uart@40028000/fpreader@ffffffff' compatible 'zeantec,jm101' has unknown vendor prefix 'zeantec'
-- Generated zephyr.dts: C:/Projects_Learn_Zephyr/zds-2002/zds-2022-drivers-app/build/zephyr/zephyr.dts
-- Generated devicetree_generated.h: C:/Projects_Learn_Zephyr/zds-2002/zds-2022-drivers-app/build/zephyr/include/generated/devicetree_generated.h
-- Including generated dts.cmake file: C:/Projects_Learn_Zephyr/zds-2002/zds-2022-drivers-app/build/zephyr/dts.cmake

C:/Projects_Learn_Zephyr/zds-2002/zds-2022-drivers-app/app/prj.conf:10: warning: attempt to assign the value 'y' to the undefined symbol LOCK

C:/Projects_Learn_Zephyr/zds-2002/zds-2022-drivers-app/app/prj.conf:13: warning: attempt to assign the value 'y' to the undefined symbol JM101_TRIGGER

error: Aborting due to Kconfig warnings

**Only simple examples work.** 
To make things a little more complicated, you must be an employee of the Nordic Semiconductor or Linux Foundation.

The authors may have the statement “it works for me.” 
Then you need to provide a description of the environment, variables, and the folder structure. 
The current documentation is very poor. 
Try to strictly follow what is written from the moment of getting started to the build of the application-example on fresh OS. 
You won't succeed.

**Comment by jpanisbl** [comment]
We fixed an issue with a customer. `uart1` must be enabled by adding `status = "okay";` in `app/boards/nrf52840dk_nrf52840.overlay`. Something like that:

```
&uart1 {
        status = "okay";
	#address-cells = <1>;
	#size-cells = <0>;

	fpreader: fpreader@ffffffff {
		compatible = "zeantec,jm101";
		reg = <0xffffffff>;
		touch-gpios = <&gpio1 4 GPIO_ACTIVE_HIGH>;
	};
};
```

**Comment by gmarull** [comment]
Fixed on `main`
